import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    breakpoints: {
      xs: number;
      sm: number;
      md: number;
      lg: number;
      xl: number;
    };
    typography: {
      fontFamily: string;
      variants: {
        display1: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        heading1: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        heading2: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        heading3: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        heading4: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        heading5: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        body1: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        body2: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        body3: FlattenInterpolation<ThemeProps<DefaultTheme>>;
        body4: FlattenInterpolation<ThemeProps<DefaultTheme>>;
      };
    };
    transition: {
      slow: string;
      normal: string;
      fast: string;
    };
    spaces: {
      xcontainer_xs: string;
      xcontainer_sm: string;
      xcontainer_md: string;
      xcontainer_lg: string;
      xcontainer_xl: string;

      'x1/1': string;
      'x1/2': string;
      'x1/3': string;
      'x2/3': string;
      'x1/4': string;
      'x2/4': string;
      'x3/4': string;
      'x1/5': string;
      'x2/5': string;
      'x3/5': string;
      'x4/5': string;
      'x1/6': string;
      'x2/6': string;
      'x3/6': string;
      'x4/6': string;
      'x5/6': string;
      'x1/12': string;
      'x2/12': string;
      'x3/12': string;
      'x4/12': string;
      'x5/12': string;
      'x6/12': string;
      'x7/12': string;
      'x8/12': string;
      'x9/12': string;
      'x10/12': string;
      'x11/12': string;

      x0: string;
      xpx: string;
      'x0.5': string;
      x1: string;
      'x1.5': string;
      x2: string;
      'x2.5': string;
      x3: string;
      'x3.5': string;
      x4: string;
      x5: string;
      x6: string;
      x7: string;
      x8: string;
      x9: string;
      x10: string;
      x11: string;
      x12: string;
      x14: string;
      x16: string;
      x20: string;
      x24: string;
      x28: string;
      x32: string;
      x36: string;
      x40: string;
      x44: string;
      x48: string;
      x52: string;
      x56: string;
      x60: string;
      x64: string;
      x72: string;
      x80: string;
      x96: string;
      xpx: string;
      'x0.5': string;
      x1: string;
      'x1.5': string;
      x2: string;
      'x2.5': string;
      x3: string;
      'x3.5': string;
      x4: string;
      x5: string;
      x6: string;
      x7: string;
      x8: string;
      x9: string;
      x10: string;
      x11: string;
      x12: string;
      x14: string;
      x16: string;
      x20: string;
      x24: string;
      x28: string;
      x32: string;
      x36: string;
      x40: string;
      x44: string;
      x48: string;
      x52: string;
      x56: string;
      x60: string;
      x64: string;
      x72: string;
      x80: string;
      x96: string;
    };
    colors: {
      transparent: string;
      alert: {
        success: string;
        warning: string;
        error: string;
      };
      neutrals: {
        '100': string;
        '200': string;
        '300': string;
        '400': string;
        '500': string;
        '600': string;
        '700': string;
        '800': string;
        '900': string;
        '999': string;
        '000': string;
        '050': string;
      };
      primary: {
        '100': string;
        '200': string;
        '300': string;
        '400': string;
        '500': string;
        '600': string;
        '700': string;
        '800': string;
        '900': string;
        '050': string;
      };
    };
    rounded: {
      full: string;
      lg: string;
      md: string;
      none: string;
      sm: string;
    };
  }
}
